ssd := ""

default:
    @just --list

build:
    make

bench ssd n:
    ./MQSim -i "ssd_config/ssd_{{ssd}}.xml" -w workload_config/iocap/synth_{{n}}.xml -o results/iocap-raw/{{ssd}}/run{{n}} 1>results/iocap-raw/{{ssd}}/run{{n}}_stdout.txt

gen-bench *args:
    mkdir -p workload_config/iocap
    uv run generate_iocap_workloads.py workload_config/iocap {{args}}

bench-all queues ssd="PM9A3": build
    mkdir -p results/iocap-raw/{{ssd}}
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_0_initial_occupancy_0
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_0_initial_occupancy_50
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_0_initial_occupancy_70
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_0_initial_occupancy_100
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_50_initial_occupancy_0
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_50_initial_occupancy_50
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_50_initial_occupancy_70
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_50_initial_occupancy_100
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_100_initial_occupancy_0
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_100_initial_occupancy_50
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_100_initial_occupancy_70
    just bench {{ssd}} len_queue_ids_{{queues}}_read_percentage_100_initial_occupancy_100

report ssd="PM9A3":
    mkdir -p results/iocap
    uv run tomlize_results.py --toml "./results/iocap/mqsim-e-results-{{ssd}}.toml" ./results/iocap-raw/{{ssd}}/run*.xml
