ssd := "ssd_config/ssd_C8_P4_64G.xml"

default:
    @just --list

build:
    make

bench n:
    ./MQSim -i {{ssd}} -w workload_config/iocap/synth_{{n}}per.xml -o results/iocap/run{{n}} 1>results/iocap/run{{n}}_stdout.txt

bench-all: build
    mkdir -p results/iocap
    just bench 1
    just bench 2
    just bench 4
    just bench 8
    just bench 16
    just bench 32
    just bench 64

report:
    uv run tomlize_results.py --toml ./results/iocap/mqsim-e-results.toml ./results/iocap/run*.xml
